# frozen_string_literal: true

# Copyright (c) 2024.
# Author: Kishor Mainali
# Company: EB Pearls
#

require 'json'

default_platform(:ios)

platform :ios do
  # authenticate with app store connect
  before_all do
    app_store_connect_api_key(
      key_id: ENV['ASC_KEY_ID'],
      issuer_id: ENV['ASC_ISSUER_ID'],
      key_content: ENV['ASC_KEY_CONTENT'],
      in_house: false,
      is_key_content_base64: true
    )
    @api_key = lane_context[SharedValues::APP_STORE_CONNECT_API_KEY]
    @app_identifier = ENV['APP_IDENTIFIER']
    @app_name = ENV['APP_STORE_APP_NAME']
    @team_id = ENV['APP_STORE_TEAM_ID']
    @app_target = ENV['APP_TARGET']
    @flutter_target = ENV['FLUTTER_TARGET']
    @flutter_flavor = ENV['FLUTTER_FLAVOR']
    @has_flavor = !@flutter_flavor.nil? && !@flutter_flavor.empty?
    @skip_app_store = ENV['SKIP_APP_STORE_CHECK']
    @workspace = ENV['WORKSPACE_FILE']
    @dart_define = nil
    if ENV['DART_DEFINE_FROM_FILE'] && !ENV['DART_DEFINE_FROM_FILE'].empty?
      @dart_define = "--dart-define-from-file=#{ENV['DART_DEFINE_FROM_FILE']}"
    end
    @firebase_credentials = ENV['FIREBASE_SERVICE_JSON_FILE']
    @firebase_app_id = ENV['FIREBASE_APP_ID']
    @flutter_command = check_fvm
    @firebase_testers_groups = ENV['FIREBASE_TESTERS_GROUPS']
    if ENV['BUILD_SCHEME'].nil? || ENV['BUILD_SCHEME'].empty?
      ENV['BUILD_SCHEME'] = 'Runner'
    end
    @dart_defines_list = []
    if ENV['DART_DEFINES'] && !ENV['DART_DEFINES'].empty?
      begin
        defines_map = JSON.parse(ENV['DART_DEFINES'])
        if defines_map.is_a?(Hash)
          defines_map.each do |k, v|
            @dart_defines_list << "--dart-define=#{k}=#{v}"
          end
        elsif defines_map.is_a?(Array)
          defines_map.each do |define|
            @dart_defines_list << "--dart-define=#{define}"
          end
        end
      rescue => e
        UI.message("Error parsing DART_DEFINES: #{e}")
      end
    end
  end


  #---------------------------------------------#
  #     CREATE AND UPLOAD BUILD FOR FIREBASE    #
  #---------------------------------------------#
  desc 'Create build for firebase'
  lane :firebase do |options|
    release = options[:release]

    # 1. get latest version from firebase
    version = get_firebase_version(release: release)
    build_version = version[:version]
    build_number = version[:build_number]

    # 2. run flutter build
    build(build_number: build_number, build_version: build_version)

    # 3. sync code signing
    match(type: 'adhoc', readonly: true, api_key: @api_key)

    # 4. generate archive
    gym

    # 5. upload to firebase
    firebase_app_distribution(
      app: @firebase_app_id,
      service_credentials_file: @firebase_credentials,
      groups: @firebase_testers_groups,
      ipa_path: '../build/ios/ipa/Runner.ipa'
    )
  end

  #---------------------------------------------#
  #     CREATE AND UPLOAD BUILD FOR TESTFLIGHT  #
  #---------------------------------------------#
  desc 'Create build for TestFlight'
  lane :test_flight do |options|
    release = options[:release]

    # 1. get latest version from TestFlight/App Store and update version
    updated_version = get_testflight_version(release: release)

    build_version = updated_version[:version]
    build_number = updated_version[:build_number]

    # 2. run flutter build
    build(build_number: build_number, build_version: build_version)

    # 3. sync code signing
    match(type: 'appstore', readonly: true, api_key: @api_key)

    # 4. generate archive
    gym

    # 5. upload to testflight
    upload_to_testflight(
      api_key: @api_key,
      ipa: '../build/ios/ipa/Runner.ipa',
      skip_submission: true,
      app_identifier: @app_identifier,
      skip_waiting_for_build_processing: true
    )
  end

  # Device management
  ######################################################################################
  #                                                                                    #
  #                                 ADD NEW DEVICE                                     #
  #                                                                                    #
  ######################################################################################
  desc 'lane to add new device and then recreate the profiles'
  lane :addDevice do
    # get the name and device id
    device_name = prompt(text: 'Enter Device Name: ')
    device_id = prompt(text: 'Enter Device Id: ')
    # add the device
    register_device(
      name: device_name,
      udid: device_id,
      team_id: @team_id,
      api_key: @api_key
    )
  end

  # certificates management
  #---------------------------------------------#
  #     CREATE NEW CERTIFICATES                 #
  #---------------------------------------------#
  desc 'Create New Certificates'
  lane :create_cert do
    get_or_create_certificates(force: true)
  end

  #---------------------------------------------#
  #     GET CERTIFICATES                        #
  #---------------------------------------------#
  desc 'Get Certificates'
  lane :get_cert do
    get_or_create_certificates(force: false)
  end

   #==================================================================#
   #                                                                  #
   #         LANE TO NUKE CERTIFICATES                                #
   #                                                                  #
   #==================================================================#
   desc "Nuke all certificates"
    lane :nuke_cert do
      match_nuke(type: "development", api_key: @api_key)
      match_nuke(type: "appstore", api_key: @api_key)
    end

  ######################################################################################
  #                                                                                    #
  #                                 ADD NEW DEVICES                                    #
  #                                                                                    #
  ######################################################################################
  desc 'lane to register multiple devices from file'
  lane :addDevices do
    register_devices(
      devices:{},
      team_id: @team_id,
      api_key: @api_key
    )
  end


  # check if fvm is installed on system then use fvm flutter command
  # if not then use flutter command
  def check_fvm
    if system('fvm --version > /dev/null 2>&1')
      'fvm flutter'
    else
      'flutter'
    end
  end

  # bump version according to semantic versioning
  def bump_version(version_str:, release_type:)
    # Check if the version string is valid
    # This regex matches semantic versioning format (X.Y.Z+X)
    # where X, Y, and Z are digits and +X is build number
    # e.g. 1.0.0+1
    unless version_str =~ /^\d+\.\d+\.\d+([+-]\d+)?$/
      raise ArgumentError, 'Invalid version string format. Expected format: x.y.z[+|-]?'
    end

    # Split the version string into version and build number
    # e.g. 1.0.0+1 => version_part = 1.0.0, build_part = 1
    # this regex captures the version part and the build number
    version_part, build_part = version_str.match(/(\d+\.\d+\.\d+)([+-]\d+)?/).captures
    # If build_part is nil, set it to 0
    build_part = build_part ? build_part[1..].to_i : 0 # remove the '+' or '-' sign
    # Increment the build number
    build_number = build_part + 1
    # If release_type is nil, return the version with incremented build number
    if release_type.nil?
      return {
        version: version_part,
        build_number: build_number
      }
    end

    # Check if the version string has exactly 3 segments and build number
    version = Gem::Version.new(version_part)
    segments = version.segments
    # Ensure version has 3 segments
    segments += [0] * (3 - segments.size)

    case release_type
    when 'major'
      segments[0] += 1
      segments[1] = 0
      segments[2] = 0
    when 'minor'
      segments[1] += 1
      segments[2] = 0
    else # patch
      segments[2] += 1
    end
    {
      version: segments[0..2].join('.'),
      build_number: build_number
    }
  end

  #==================================================================#
  #                                                                  #
  #         FUNCTION TO GET VERSION FROM FIREBASE                    #
  #                                                                  #
  #==================================================================#
  def get_firebase_version(release:)
    # get the latest version from firebase
    firebase_app_distribution_get_latest_release(
      app: @firebase_app_id,
      service_credentials_file: @firebase_credentials
    )
    latest_release = lane_context[SharedValues::FIREBASE_APP_DISTRO_LATEST_RELEASE]
    version_str = if latest_release.nil?
                    '1.0.0+0'
                  else
                    "#{latest_release[:displayVersion]}+#{latest_release[:buildVersion]}"
                  end
    # bump version
    bump_version(
      version_str: version_str,
      release_type: release
    )
  end

  #---------------------------------------------#
  #     GET AND BUMP VERSION FROM TESTFLIGHT    #
  #---------------------------------------------#
  def get_testflight_version(release:)
    begin
      # get the latest build number and version name from testflight
      latest_testflight_build_number(
        api_key: @api_key,
        team_id: @team_id,
        app_identifier: @app_identifier
      )

      # get build number
      tf_build_number = lane_context[SharedValues::LATEST_TESTFLIGHT_BUILD_NUMBER]

      # get version name
      tf_version_name = lane_context[SharedValues::LATEST_TESTFLIGHT_VERSION]

      version_str = if tf_build_number.nil? || tf_version_name.nil?
                      '1.0.0+0'
                    else
                      "#{tf_version_name}+#{tf_build_number}"
                    end

      # get the latest version from App Store if skip_appstore is false
      if @skip_app_store == 'false'

        # get the latest version from App Store
        app_store_build_number(api_key: @api_key, team_id: @team_id, app_identifier: @app_identifier)

        # get build number
        live_build_number = lane_context[SharedValues::LATEST_BUILD_NUMBER]

        # get version name
        live_version_name = lane_context[SharedValues::LATEST_VERSION]

        # set live version if current tf version is alredy released
        unless live_build_number.nil? || live_version_name.nil?
          live_version = Gem::Version.new(live_version_name)
          tf_version = Gem::Version.new(tf_version_name)
          if live_version == tf_version || live_version > tf_version
            version_str = "#{live_version_name}+#{live_build_number}"
            release = 'patch' if release.nil?
          end
        end
      end
    rescue StandardError => error
      UI.message("No build found in testflight or appstore #{error}")
      version_str = "#{tf_version_name}+#{tf_build_number}" if tf_build_number && tf_version_name else '1.0.0+0'
    end

    # bump version
    bump_version(
      version_str: version_str,
      release_type: release
    )
  end

  # generate/get certificates and install profiles
  def get_or_create_certificates(force:)
    match(type: 'development', force: force, readonly: !force, api_key: @api_key)
    match(type: 'adhoc', force: force, readonly: !force, api_key: @api_key)
    match(type: 'appstore', force: force, readonly: !force, api_key: @api_key)
  end

  #---------------------------------------------#
  #     GENERATE BUILD                          #
  #---------------------------------------------#
  def build(build_number:, build_version:)
    raise ArgumentError, 'Missing build number and build version' if build_number.nil? && build_version.nil?

    cmd = [@flutter_command, 'build', 'ios', '--release', '--no-codesign', '--config-only']
    cmd.concat(['--flavor', @flutter_flavor]) if @has_flavor
    cmd.concat([
      '-t', @flutter_target,
      '--build-number', build_number,
      '--build-name', build_version.to_s
    ])
    cmd.push(@dart_define) if @dart_define
    cmd.concat(@dart_defines_list) if @dart_defines_list

    sh cmd.compact
  end

end
