source "https://rubygems.org"

gem "fastlane", '>= 2.236.1'
gem "dotenv", '< 3.0.0'
gem 'nokogiri', '>= 1.19.4'
gem "abbrev", '0.1.2'
gem "ostruct", '0.6.3'
gem "cocoapods", '1.16.2'


plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
