# .github/workflows/publish.yml
name: Publish to pub.dev
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*" # for tags like: 'v1.2.3'
      - "v[0-9]+.[0-9]+.[0-9]+*-dev.[0-9]+" # for tags like: 'v1.2.3-dev.1'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: 📦 Install Dependencies
        run: flutter pub get

      - name: 📝 Format Code
        run: dart format .

      - name: 📝 Analyze Code
        run: dart analyze .

      - name: 🚀 Publish package
        run: dart pub publish -f
