# .github/workflows/pull-request.yml
name: Review PR
on:
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4

      - name: 🐦 Setup Dart
        uses: dart-lang/setup-dart@v0
        with:
          channel: stable
          cache: true

      - name: 📦 Install Dependencies
        run: dart pub get

      - name: 📝 Format Code
        run: dart format .

      - name: 📝 Analyze Code
        run: dart analyze .
